title: "César Feniou"
description: "Postdoctoral Researcher in Quantum Algorithms"
url: "https://cesarfeniou.github.io"
baseurl: ""

markdown: kramdown

permalink: pretty

plugins:
  - jekyll-scholar

scholar:
  source: _bibliography
  bibliography: papers.bib
  template: bib   
  style: apa
  sort_by: year
  order: descending
